/*------------------------------------------------------------------------------
 * Programmer: Michael Ubert
 * Date: 2/15/15
 * Name: hw1.c
 * Description: Code for a weather temperature conversion training system to
 * ensure elementary students can perform conversions between Celsius and Fahrenheit.
 -------------------------------------------------------------------------------*/
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define MAXTEMP 100
#define MINTEMP -100


char getCharacterFrmKeyBoard();
int FahrenheitToCelsius(float F);
int CelsiusToFahrenheit(float C);
int wrongFahrenheitToCelsius(float F, int i);
int wrongCelsiusToFahrenheit(float C, int i);

int main( void )
{

    int score = 0;
    int temperature;
    char studentAnswer;
    int scale = 0;
    int correct = 0;
    float temp = 0;
    int wrong_1 = 0;
    int wrong_2 = 0;
    char exit = 'c';
    int total = 0;
    int percentage = 0;
    int scale = 0;

    // Initialize the random number generator with a seed based on current time
    // This will ensure that the random number generated by the program will be
    srand(time(NULL));

    printf("Welcome to the temperature conversion training system.\n");

    while(exit != 'x')
    {
        //Random numbers for starting temperature scale and temperature
        scale = rand()%2;
        temperature = 2*(rand()%MAXTEMP) - 100;

        //Determine if starting from Fahrenheit or Celsius and create a correct answer
        //two incorrect answers
        if(scale == 0)
        {
            printf("Convert %d F to C\n", temperature);
            temp = temperature;
            correct = FahrenheitToCelsius(temp);
            wrong_1 = wrongFahrenheitToCelsius(temp, 1);
            wrong_2 = wrongFahrenheitToCelsius(temp, 2);
        }
        else
        {
            printf("Convert %d C to F\n",temperature);
            temp = temperature;
            correct = CelsiusToFahrenheit(temp);
            wrong_1 = wrongCelsiusToFahrenheit(temp, 1);
            wrong_2 = wrongCelsiusToFahrenheit(temp, 2);
        }

        //Randomly assign the three possible answers and display them to the user.
        //Also take the student's response and determine if the student answered correctly
        switch(rand()%3)
        {
            case 0:
                printf("a. %d b. %d c. %d\n", correct, wrong_1, wrong_2);
                studentAnswer = getCharacterFrmKeyBoard();
                if(studentAnswer == 'a')
                {
                    printf("Correct.\n");
                    score = score + 1;
                }
                else
                {
                    printf("Incorrect. The correct answer is a. %d\n", correct);
                }
                break;
            case 1:
                printf("a. %d b. %d c. %d\n", wrong_1, correct, wrong_2);
                studentAnswer = getCharacterFrmKeyBoard();
                if(studentAnswer == 'b')
                {
                    printf("Correct.\n");
                    score = score + 1;
                }
                else
                {
                    printf("Incorrect. The correct answer is b. %d\n", correct);
                }
                break;
            case 2:
                printf("a. %d b. %d c. %d\n", wrong_1, wrong_2, correct);
                studentAnswer = getCharacterFrmKeyBoard();
                if(studentAnswer == 'c')
                {
                    printf("Correct.\n");
                    score = score + 1;
                }
                else
                {
                    printf("Incorrect. The correct answer is c. %d\n", correct);
                }
                break;
        }
        total = total + 1;
        printf("Press 'x' to exit, any other key to continue to another question.\n");
        exit = getCharacterFrmKeyBoard();
    }

    //Print the score and percent correct back to the user
    printf("Thank you for using conversion training system system.\n");
    percentage = (100*score)/total;
    printf("You got %d out of %d questions right! That is %d percent correct!", score, total, percentage);

    return 0;
}

/*---------------------------------------------------------------------------------
 * Function name: getCharacterFrmKeyBoard
 * Inputs a character from the keyboard
 * Removes unwanted newline characters in the input stream
 * Read the help file on ICON HW1 description for details
 --------------------------------------------------------------------------------*/
char getCharacterFrmKeyBoard()
{
    char discard,ch;

    do{
        ch=getchar();
    } while (ch=='\n');

    do{
        discard=getchar();
    } while (discard!='\n');

    return(ch);
}

/*---------------------------------------------------------------------------------
 * Function name: FahrenheitToCelsius
 * Converts a temperature in Fahrenheit to Celsius and rounds it to the nearest
 * integer.
 --------------------------------------------------------------------------------*/
int FahrenheitToCelsius(float F)
{
    float C = 0;

    C = (F - 32) * 5/9;

    if(C > 0)
    {
        C = C + 0.5;
    }
    else
    {
        C = C - 0.5;
    }

    return C;
}

/*---------------------------------------------------------------------------------
 * Function name: CelsiusToFahrenheit
 * Converts a temperature in Celsius to Fahrenheit and rounds it to the nearest
 * integer.
 --------------------------------------------------------------------------------*/
int CelsiusToFahrenheit(float C)
{
    float F = 0;

    F = ((9*C)/5) + 32;

    if(F > 0)
    {
        F = F + 0.5;
    }
    else
    {
        F = F - 0.5;
    }

    return F;
}

/*---------------------------------------------------------------------------------
 * Function name: wrongFahrenheitToCelsius
 * Creates a wrong answer for converting a temperature in Fahrenheit to Celsius
 --------------------------------------------------------------------------------*/
int wrongFahrenheitToCelsius(float F, int i)
{
    float C = 0;

    if(i == 1)
    {
        C = ((F*5)/9) - 32;

        if(C > 0)
        {
            C = C + 0.5;
        }
        else
        {
            C = C - 0.5;
        }
    }
    else
    {
        C = ((F*5) - 32)/9;

        if(C > 0)
        {
            C = C + 0.5;
        }
        else
        {
            C = C - 0.5;
        }
    }

    return C;
}

/*---------------------------------------------------------------------------------
 * Function name: wrongCelsiusToFahrenheit
 * Creates a wrong answer for converting a temperature in Celsius to Fahrenheit
 --------------------------------------------------------------------------------*/
int wrongCelsiusToFahrenheit(float C, int i)
{
    float F = 0;

    if(i == 1)
    {
        F = ((C + 32)*9)/5;

        if(F > 0)
        {
            F = F + 0.5;
        }
        else
        {
            F = F - 0.5;
        }
    }
    else
    {
        F = ((C*9) + 32)/5;

        if(F > 0)
        {
            F = F + 0.5;
        }
        else
        {
            F = F - 0.5;
        }
    }

    return F;
}
